### ISSUE TITLE
Responsivity problem in the "Section Programme" in the home page.

### ISSUE THREAD

**Issue by Naoufal-jrh** [ibtissammassa/Site-formation-ensa#2]
This section does't look fine, idk if you saw it or not, here is a screenshot 
![image](https://github.com/ibtissammassa/Site-formation-ensa/assets/75337660/6737547b-4de9-4a1b-8d70-fa6e27d146e1)
just close this issue if you made it look like that on perpose.

**Comment by ibtissammassa** [comment]
I've addressed the responsiveness issues and any related bugs in this section

![image](https://github.com/ibtissammassa/Site-formation-ensa/assets/75497523/abfaca5d-0113-46fb-ab29-d2f5bd2a7992)

![image](https://github.com/ibtissammassa/Site-formation-ensa/assets/75497523/42ac41b2-1cf7-4af6-8a52-cd4b07ca6647)

> If you notice any other issues or bugs from this section please feel free to share
