### ISSUE TITLE
front end problem, z index modification needed

### ISSUE THREAD

**Issue by Naoufal-jrh** [ibtissammassa/Site-formation-ensa#4]
When the drop down menu is openned, the cover image from the course card shows on top of the menu, see the screenshot
![image](https://github.com/ibtissammassa/Site-formation-ensa/assets/75337660/13633256-e490-4411-affc-7b104dd22d31)
i think if we change the indes of the menu to z-10 the bug will be fixed

**Comment by ibtissammassa** [comment]
Great catch! I've just fixed the issue by adjusting the z-index of the menu to z-50 and it's working :)))

![image](https://github.com/ibtissammassa/Site-formation-ensa/assets/75497523/64ecccb6-7dfb-4d38-a5a1-c9aacbdc8abc)
